# -*- coding: utf-8 -*-
"""Bank+.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2LHMbonxlLZAlpUJPnbXfNpZzQIKvXl
"""

!pip install tabula-py

import tabula
import pandas as pd
from tabula.io import read_pdf
import os
import re
import warnings

# Creating a dictionary with keys as bank names and assigning indexes to each column
Bank_statement_features = {
   'ICICI':
   {
       'Date':0,
       'Particulars':1,
       'Chq.No.':2,
       'Withdrawals':3,
       'Deposits':4,
       'Auto Sweep':5,
       'Reverse Sweep':6,
       'Balance(INR)':7,
   },#can further add features according to "bank name as keys" of the dictionary
}

# Using Tabula(an open source library) to extract tables from a pdf with much accuracy
# here using tabula-py(Python wrapper of tabula)
#setting the values of various parameters
filepath = r"/content/ICICI_Bank_Statement.pdf"
rows_list = tabula.read_pdf(filepath,pages='1',silent=True,stream=True,lattice=True,guess=False,
                            area = (320.0,9.0,743.81,601.11),encoding='utf-8')
                            #area refers to the Portion of the page to analyze(top,left,bottom,right).
                            # calulated using tabula script exporter

                            #pandas_options={'header': None,'error_bad_lines': False,'warn_bad_lines': False}
                            #pandas_options not needed when multiple_tabels=True


#converting the lists together into a dataFrame
rows_df = pd.DataFrame(rows_list[0],
                       columns = ['Date','Particulars','Chq.No.','Withdrawals','Deposits',
                                  'Auto Sweep','Reverse Sweep','Balance(INR)','Credit','Debit'])

#Removing unnecessary columns and rows
rows_df.drop(['Auto Sweep','Reverse Sweep'],axis=1,inplace=True)
rows_df.drop([0],inplace=True)

# tackling those entries which contain delimeter like ','
for i in range(1,len(rows_df)+1):
    rows_df['Withdrawals'][i] = rows_df['Withdrawals'][i].replace(',','')
    rows_df['Deposits'][i] = rows_df['Deposits'][i].replace(',','')

#converting string values to float so that airthmetic analysis can be made
rows_df["Withdrawals"] = pd.to_numeric(rows_df["Withdrawals"], downcast="float",errors='ignore')
rows_df["Deposits"] = pd.to_numeric(rows_df["Deposits"], downcast="float",errors='ignore')
5
rows_df

#same code when all the pages are need to be covered
aux_list = tabula.io.read_pdf(filepath,
                     guess=False, pages='all', stream=False ,silent=True ,encoding="utf-8",
                     area = ( 320.0,9.0,743.81,601.11 ))
                     #columns = (65.3,196.86,294.96,351.81,388.21,429.77))

aux_df = pd.DataFrame(aux_list[0],
                      columns = ['Date','Particulars','Chq.No.','Withdrawals','Deposits',
                                 'Auto Sweep','Reverse Sweep','Balance(INR)','Credit','Debit'])

aux_df.drop(['Auto Sweep','Reverse Sweep'],axis=1,inplace=True)
aux_df.drop([0],inplace=True)

for i in range(1,len(aux_df)):
    aux_df['Withdrawals'][i] = aux_df['Withdrawals'][i].replace(',','')
    aux_df['Deposits'][i] = aux_df['Deposits'][i].replace(',','')

aux_df["Withdrawals"] = pd.to_numeric(aux_df["Withdrawals"], downcast="float",errors='ignore')
aux_df["Deposits"] = pd.to_numeric(aux_df["Deposits"], downcast="float",errors='ignore')

aux_df

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=aux_df)